version: '3.4'
services:

  iotsharp:
    image: maikebing/iotsharp
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - "./appsettings.Development.json:/app/appsettings.Production.json"
      - ./data/security:/app/security
    ports:
      - 502:502
      - 2929:8888
      - 1883:1883
      - 8883:8883 
      - 5683:5683
      - 5684:5684